### ISSUE TITLE
M2 Mac 无法使用APP中的谷歌翻译服务

### ISSUE THREAD

**Issue by Chanhao** [xiaomaoJT/QxScript#1]
1、问题设备：M2 芯片 MacBook Air 使用 QX 作为翻墙工具
2、问题：M2 MacBook Air 的网页可以登录/使用谷歌翻译服务，但是一些app中的翻译服务(谷歌翻译)就无法使用 --  比如第三方推特客户端 Spring for Twitter 中的翻译服务；
           
3、但是：①M2 MacBook Air 的翻墙工具如果换成小火箭 Shadowrocket，这些app中的翻译服务是可以用的（谷歌翻译）；
                 ②iPhone上使用QX，使用跟 M2 MacBook Air 端的QX完全一模一样的配置，却又是可以正常使用app中的翻译服务的（谷歌翻译）

4、我用了你的xiaomao规则，同时也用了其他几家的规则，都存在这个问题，所以理论上应该不是规则的问题？不知道大佬清不清楚这个问题的原因，这个问题困扰我很久了，感谢！
<img width="462" alt="CleanShot 2023-04-28 at 17 53 21" src="https://user-images.githubusercontent.com/8262705/235116584-0a0fb8c7-fb57-487a-bf8c-e542cbbd53e1.png">

**Comment by xiaomaoJT** [comment]
哈喽，认真看了你的问题，因为Spring for Twitter需付费下载无法直接复现问题。

个人猜测原因：qx并未有真正意义上的for mac版本，也正如你所说的非规则问题，故推测可能是软件的bug（或可使用全局模式看是否仍无法使用），我在使用mac端qx时也遇到很多问题如dns解析缓慢等，建议mac端使用其他替代工具，如clashx pro等等。可参考clash配置仓库https://github.com/xiaomaoJT/clash

**Comment by Chanhao** [comment]
> 哈喽，认真看了你的问题，因为Spring for Twitter需付费下载无法直接复现问题。
> 
> 个人猜测原因：qx并未有真正意义上的for mac版本，也正如你所说的非规则问题，故推测可能是软件的bug（或可使用全局模式看是否仍无法使用），我在使用mac端qx时也遇到很多问题如dns解析缓慢等，建议mac端使用其他替代工具，如clashx pro等等。可参考clash配置仓库https://github.com/xiaomaoJT/clash

**Comment by Chanhao** [comment]
感谢~
