### ISSUE TITLE
Mac圈X规则 openai分流显示404了

### ISSUE THREAD

**Issue by dqzboy** [xiaomaoJT/QxScript#2]
Mac圈X规则 openai分流显示404了，如下图

<img width="457" alt="image" src="https://github.com/xiaomaoJT/QxScript/assets/42825450/8c1ac0e2-8d1e-4371-b954-4f3b75e6c97f">

**Comment by xiaomaoJT** [comment]
更新地址：
https://raw.githubusercontent.com/xiaomaoJT/QxScript/main/filter/yaml/OpenAi.yaml
或者
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/OpenAI/OpenAI.list

**Comment by dqzboy** [comment]
> 更新地址： https://raw.githubusercontent.com/xiaomaoJT/QxScript/main/filter/yaml/OpenAi.yaml 或者 https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/OpenAI/OpenAI.list

以修改，下面链接可以，上面链接会提示无效的URL

**Comment by xiaomaoJT** [comment]
第一个yaml格式，需打开解析器

**Comment by dqzboy** [comment]
> 第一个yaml格式，需打开解析器

好的 明白了 谢谢回复

**Comment by dqzboy** [comment]
在反馈一个问题，就是coze.com分流好像走的是国内地区或者香港地区

**Comment by xiaomaoJT** [comment]
应用分流大部分来自它库引用或AI抓取，不作维护。coze.com如果是openai域名，可于本地自行添加后走openai策略哈。
「本库脚本如有问题我才能解决」
